### ISSUE TITLE
Doesn't handle whitespace in paths

### ISSUE THREAD

**Issue by pahwaranger** [sbdchd/codeowners#34]
While it is rare and not good practice, some directories may have whitespace in them. The current logic does a simple `split()` which does not properly handle this case and causes missed matches. CODEOWNERS itself _does_ support whitespace in paths.

example:
```py
from codeowners import CodeOwners

example_file = """\
# path with whitespace
/whitespace\ test/    @ghost
"""

owners = CodeOwners(example_file)
print(owners.of("whitespace\ test/test.py"))  # []
```

example of it working if we replace whitespace with a `_`:
```py
from codeowners import CodeOwners

example_file = """\
# path with whitespace
/whitespace_test/    @ghost
"""

owners = CodeOwners(example_file)
print(owners.of("whitespace_test/test.py"))  # [('USERNAME', '@ghost')]
```

**Comment by pahwaranger** [comment]
this was fixed in the above PR

**Comment by pahwaranger** [comment]
reopening because related code hasn't been included in a release yet

**Comment by sbdchd** [comment]
should be fixed in the latest release

**Comment by nickkaczmarek** [comment]
Hello, I think this is still an issue.

```python
from codeowners import CodeOwners

example_codeowners = """\
# example codeowners file
SharedCells Headers/SomeFile.xib 	@reviewers/team1 @reviewers/team2
SharedCells Headers/SomeFile2.swift @reviewers/team1 @reviewers/team3
SharedCells Headers/SomeFile3.swift @reviewers/team1 @reviewers/team2
SharedCells Headers/SomeFile4.swift @reviewers/team1 @reviewers/team3
"""

owners = CodeOwners(example_codeowners)

print(owners.of("SharedCells Headers/SomeFile.xib"))
print(owners.of("SharedCells Headers/SomeFile2.swift"))
print(owners.of("SharedCells Headers/SomeFile3.swift"))
print(owners.of("SharedCells Headers/SomeFile4.swift"))
```

## Output:

```
[('TEAM', '@reviewers/team1'), ('TEAM', '@reviewers/team3')]
[('TEAM', '@reviewers/team1'), ('TEAM', '@reviewers/team3')]
[('TEAM', '@reviewers/team1'), ('TEAM', '@reviewers/team3')]
[('TEAM', '@reviewers/team1'), ('TEAM', '@reviewers/team3')]
```

And if I remove the spaces like so:

```python
from codeowners import CodeOwners

example_codeowners = """\
# example codeowners file
SharedCellsHeaders/SomeFile.xib 	@reviewers/team1 @reviewers/team2
SharedCellsHeaders/SomeFile2.swift @reviewers/team1 @reviewers/team3
SharedCellsHeaders/SomeFile3.swift @reviewers/team1 @reviewers/team2
SharedCellsHeaders/SomeFile4.swift @reviewers/team1 @reviewers/team3
"""

owners = CodeOwners(example_codeowners)

print(owners.of("SharedCellsHeaders/SomeFile.xib"))
print(owners.of("SharedCellsHeaders/SomeFile2.swift"))
print(owners.of("SharedCellsHeaders/SomeFile3.swift"))
print(owners.of("SharedCellsHeaders/SomeFile4.swift"))
```

## The output is correct:

```
[('TEAM', '@reviewers/team1'), ('TEAM', '@reviewers/team2')]
[('TEAM', '@reviewers/team1'), ('TEAM', '@reviewers/team3')]
[('TEAM', '@reviewers/team1'), ('TEAM', '@reviewers/team2')]
[('TEAM', '@reviewers/team1'), ('TEAM', '@reviewers/team3')]
```
